package ifl.agentbreaker.conversationmanager.domain.dtos.responses;

import ifl.agentbreaker.conversationmanager.domain.constants.MessageRole;
import lombok.Data;

@Data
public class ConversationMessageInfo
{
    private long id;

    /**
     * Role of the message.
     */
    private MessageRole role;

    /**
     * Text content of the message.
     */
    private String content;

    /**
     * ID of the agent that generated this message.
     * {@code null} if the message is not generated by an agent but a user or a tool call.
     */
    private Long agentId;

    /**
     * ID of the tool call request/response.
     * {@code null} if the message is not a tool call request/response.
     */
    private String toolCallId;
}
