package ifl.agentbreaker.conversationmanager.domain.dtos.requests;

import ifl.agentbreaker.conversationmanager.domain.constants.GeneratedOutputKind;
import ifl.agentbreaker.conversationmanager.domain.constants.GenerationAttemptStatus;
import ifl.agentbreaker.conversationmanager.domain.constants.EditResolutionKind;
import lombok.Builder;

import java.time.Instant;

/**
 * One terminal generation attempt submitted by Agent Runner for durable materialization. The
 * builder keeps call sites readable and prevents positional mistakes across the audit fields.
 *
 * @param userId authenticated owner of the Conversation
 * @param conversationId stable Conversation identifier
 * @param roundNumber Round that produced the attempt
 * @param attemptId Runner-supplied idempotency identity for the attempt
 * @param capabilityKey capability that produced the attempt
 * @param model provider model identifier recorded for audit
 * @param status terminal attempt status reported by Runner
 * @param sourceTurnNumber Turn that owns the capability execution
 * @param originalFilename display filename kept as metadata only
 * @param mimeType declared output MIME type
 * @param content generated bytes, empty when the attempt produced no artifact
 * @param sha256 checksum supplied for already validated bytes
 * @param width validated pixel width, zero when unknown
 * @param height validated pixel height, zero when unknown
 * @param outputKind generic generated output kind
 * @param rewrittenInstruction bounded instruction produced for the Task Agent
 * @param providerRequestId bounded provider request identifier
 * @param errorCode client-safe failure classification
 * @param errorMessage client-safe failure message
 * @param startTime provider execution start
 * @param endTime provider execution end, null while undetermined
 * @param requestId request correlation identifier
 * @param traceId distributed trace identifier
 * @param taskAgentId Task-Agent identity recorded for audit, zero when not applicable
 * @param taskAgentName Task-Agent name recorded for audit
 * @param taskAgentVersion Task-Agent version recorded for audit
 * @param normalizedSettingsJson bounded provider settings captured for replay
 * @param parentSpanId capability span that owns the Task-Agent execution
 * @param taskSpanId Task-Agent execution span
 * @param editResolutionKind method used to choose the single edit source image, or null for
 *        ordinary generation
 * @param editSourceFileId stable source image file ID for an edit attempt, or an empty value for
 *        ordinary generation
 * @param editSourceRoundNumber Round that produced or attached the source image, or zero when
 *        unknown
 * @param referenceResolution resolver audit when the source image was chosen by the
 *        image-reference-resolver Task Agent, otherwise null
 */
@Builder
public record GeneratedFileMaterializationRequest(
    long userId,
    String conversationId,
    long roundNumber,
    String attemptId,
    String capabilityKey,
    String model,
    GenerationAttemptStatus status,
    long sourceTurnNumber,
    String originalFilename,
    String mimeType,
    byte[] content,
    String sha256,
    int width,
    int height,
    GeneratedOutputKind outputKind,
    String rewrittenInstruction,
    String providerRequestId,
    String errorCode,
    String errorMessage,
    Instant startTime,
    Instant endTime,
    String requestId,
    String traceId,
    long taskAgentId,
    String taskAgentName,
    int taskAgentVersion,
    String normalizedSettingsJson,
    String parentSpanId,
    String taskSpanId,
    EditResolutionKind editResolutionKind,
    String editSourceFileId,
    long editSourceRoundNumber,
    ReferenceResolutionAudit referenceResolution)
{
}
