package ifl.agentbreaker.conversationmanager.domain.entities.pg;

import ifl.agentbreaker.conversationmanager.domain.constants.MessageRole;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class ConversationMessage extends EntityBase
{
    /**
     * Role of the message.
     */
    private MessageRole role;

    /**
     * Text content of the message.
     */
    private String content;

    /**
     * ID of the agent that generated this message.
     * {@code null} if the message is not generated by an agent but a user or a tool call.
     */
    private Long agentId;

    /**
     * ID of the tool call request/response.
     * {@code null} if the message is not a tool call request/response.
     */
    private String toolCallId;

    /**
     * Whether the message has been deleted logically.
     */
    // Here we use a logic deletion instead of a hard deletion because the shared conversation may contain the deleted message, since the shared conversation is a snapshot of the parent conversation.
    private boolean deleted;

    // TODO: embedding.

    // TODO: Add support for multimodality.
}
