package ifl.agentbreaker.conversationmanager.domain.entities.pg;

import ifl.agentbreaker.conversationmanager.api.constants.MessageRole;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class ConversationMessage extends EntityBase
{
    /**
     * ID of the conversation that the message belongs to.
     */
    private String conversationId;

    /**
     * Role of the message.
     */
    private MessageRole role;

    /**
     * Name of the participant or tool.
     * Used for tool messages to identify which tool was called.
     */
    private String name;

    /**
     * Text content of the message.
     * For backward compatibility and simple text messages.
     * If contentParts is not null, this field may be null.
     */
    private String content;

    /**
     * Multimodal content parts in JSON format.
     * Structure: [{"type": "text|image_url|input_image|generated_image", "text": "...", "image_url": {"url": "...", "fileId": "..."}}]
     * Null for text-only messages.
     */
    private String contentParts;

    /**
     * Tool calls in JSON format.
     * Structure: [{"id": "call_xxx", "type": "function", "function": {"name": "...", "arguments": "..."}}]
     * Only present for ASSISTANT messages that make tool calls.
     */
    private String toolCalls;

    /**
     * ID of the tool call this message is responding to.
     * Only present for TOOL role messages.
     */
    private String toolCallId;

    /**
     * ID of the agent that generated this message.
     * Null if the message is not generated by an agent.
     */
    private Long agentId;

    /**
     * Reason why the generation finished.
     * Values: "stop", "tool_calls", "length", "content_filter", etc.
     */
    private String finishReason;

    /**
     * Whether the message has been deleted logically.
     */
    private boolean deleted;
}
